### ISSUE TITLE
rtl8821ce requires fix for kernel 5.10

### ISSUE THREAD

**Issue by buboleck** [dallenwilson/trolltoo#3]
Hello,

The rtl8821ce driver requires a fix for 5.10 kernels, it is already fixed, could you please update the ebuild:

https://github.com/tomaspinho/rtl8821ce

Kind regards.

**Comment by dallenwilson** [comment]
Done.

If you haven't yet, try the in-kernel rtw88 driver along with the firmware from sys-kernel/linux-firmware. There are a few 8821ce chipsets out there that work with it.

**Comment by buboleck** [comment]
Thanks, unfortunately mine is not supported yet by the rtw88.
