### ISSUE TITLE
rtl8821ce module not loading in kernel 5.11

### ISSUE THREAD

**Issue by develBuzz** [dallenwilson/trolltoo#5]
Hi, 
first of all thank you for keeping the overlay alive. It makes my wifi usable again. 

Symtom: 
======
after booting into kernel 5.11 module was not loaded and "insmod" reported that the module is not installed, but "find /lib/modules/5.11.0-gentoo/ -name "8821ce.ko" listed it in it's usual place. 

emerge was fine too, no error. 

After some digging i found https://bugs.archlinux.org/task/69655 which stated that "pahole" is needed for dkms modules as of kernel 5.11. 

Solution:
======
emerge -av dev-util/dwarves

It contains pahole, after a rebuild and a restart the module was loaded and is working. 

Greetings.

P. S. It seems realtek is fixing device support in kernel 5.12 too, see https://aur.archlinux.org/packages/rtl8821ce-dkms-git/

**Comment by dallenwilson** [comment]
Thanks, I'll update the ebuild.

**Comment by dallenwilson** [comment]
Pushed an update, kindly let me know if it takes care of the problem.

**Comment by develBuzz** [comment]
Works for me.
Steps:
emerge --sync
Removed driver and dwarves (--deselect + --depclean) 
Reboot. 
emerge -av net-wireless/rtl8821ce-driver

Tyvm.
