### ISSUE TITLE
Update rtl8821ce to support 5.18

### ISSUE THREAD

**Issue by karimrir1** [dallenwilson/trolltoo#8]
With the merge of https://github.com/tomaspinho/rtl8821ce/pull/275, rtl8821ce now supports 5.18.

**Comment by dallenwilson** [comment]
Pushed an updated ebuild. Let me know if it works, I've only got one machine with that chipset in it, and I don't have it handy for testing right now.

**Comment by dallenwilson** [comment]
Seems to work on the one machine I use it on, so I'll go ahead and close this.
